name: PersonalityTest
options:
  bundleIdPrefix: com.personality.test
  postGenCommand: pod install
targets:
  PersonalityTest:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    sources: 
      - path: PersonalityTest
      - path: Server/public/personality_test.json
        createIntermediateGroups: false
        group: PersonalityTest/Resources
  PersonalityTestTests:
    platform: iOS
    sources: [PersonalityTestTests]
    type: bundle.unit-test
  PersonalityTestUITests:
    platform: iOS
    sources: [PersonalityTestUITests]
    type: bundle.ui-testing

