name: PersonalityTest
options:
  bundleIdPrefix: com.personality.test
  postGenCommand: pod install
targets:
  PersonalityTest:
    type: application
    platform: iOS
    deploymentTarget: "11.0"
    settings:
      API_BASE_URL: http://127.0.0.1:3000
    dependencies:
      - framework: Networking.framework
        implicit: true
    scheme: {}
    sources: 
      - path: PersonalityTest
      - path: Server/public/personality_test.json
        createIntermediateGroups: false
        group: PersonalityTest/Resources
      - path: Networking/Networking.xcodeproj
        group: Dependencies
  PersonalityTestTests:
    platform: iOS
    sources: [PersonalityTestTests]
    type: bundle.unit-test
    dependencies:
    - target: PersonalityTest
    scheme: 
      testTargets: 
      - PersonalityTestTests
      gatherCoverageData: true
      coverageTargets: 
      - PersonalityTest
  PersonalityTestUITests:
    platform: iOS
    sources: [PersonalityTestUITests]
    type: bundle.ui-testing
    dependencies:
    - target: PersonalityTest
    scheme: 
      testTargets: 
      - PersonalityTestUITests

